api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: /etc/traefik/config
    watch: true
  docker: 
    exposedByDefault: false

log:
  level: INFO

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          permanent: false
  https:
    address: ":443"


