---
- name: Run a shell command
  hosts: all
  tasks:
    - name: Add Nodesource apt key.
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present
    - name: Add NodeSource repositories for Node.js.
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - "deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
    - name: Install nodejs
      apt:
        name: nodejs
        state: latest
        update_cache: yes
    - name: Install "serve" node.js package      
      npm:
        name: serve
        global: yes
    - name: Start serve js 
      shell: serve -l 80