---
- name: Install required system packages
  hosts: all
  tasks:
    - name: Install requirement for htpasswd
      apt: 
        pkg:
          - python3-passlib

    - name: Hash a password in MD5
      community.general.htpasswd:
        path: /srv/siteweb_asso/traefik/passwordFile
        name: test
        password: 'password'
        hash_scheme: md5_crypt