---
- name: Set up Traefik with Docker for secure connections
  hosts: all
  tasks:
    - name: Create a network for all containers
      docker_network:
        name: siteweb_asso

    - name: Traefik static config file
      ansible.builtin.template:
        dest: /srv/siteweb_asso/traefik/
        src: "../traefik/traefik.yml"

    - name: Set up Traefik
      docker_container:
        name: traefik_container
        image: traefik:latest
        state: started
        restart: true
        ports:
          - "80:8080"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /srv/siteweb_asso/traefik/:/etc/traefik/
        networks:
          - name: siteweb_asso