api:
  insecure: false
  dashboard: true

providers:
  file:
    directory: /etc/traefik/config
    watch: true

log:
  level: DEBUG

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          permanent: false
  https:
    address: ":443"


