---
- name: Deploy MySQL Container
  hosts: all
  vars: 
    mysql: 
      - mysql-db
      - mysql-user
      - mysql-password
  tasks:
    - name: Pull MySQL image
      docker_image:
        name: mysql:5.7
        source: pull

    - name: Run MySQL container
      docker_container:
        name: mysql-container
        image: mysql:5.7
        restart: true
        env:
          MYSQL_ROOT_PASSWORD: examplepass
          MYSQL_DATABASE: "{{ mysql[0] }}"
          MYSQL_USER: "{{ mysql[1] }}"
          MYSQL_PASSWORD: "{{ mysql[2] }}"
        volumes:
          - mysql_data:/var/lib/mysql

    - name: Pull WordPress image
      docker_image:
        name: wordpress:latest
        source: pull

    - name: Run WordPress container
      docker_container:
        name: wordpress-container
        image: wordpress:latest
        links:
          - "mysql-container:mysql"
        ports:
          - "80:80"
        env:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: "{{ mysql[1] }}"
          WORDPRESS_DB_PASSWORD: "{{ mysql[2] }}"
          WORDPRESS_DB_NAME: "{{ mysql[0] }}"